[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build --workspace=apps/api",
  "npx prisma generate --schema apps/api/prisma/schema.prisma",
  "npx prisma generate --schema apps/api/prisma/tenant/schema.prisma"
]

[start]
cmd = "node apps/api/dist/index.js"
